#!/bin/sh
# mangle_paths by chuno (Chief Unoriginal)
# Free to use however.
#
# THIS IS NO LONGER OF ANY USE TO ANYONE.
#
# no arguments
# This has the effect on working dir of 02add_lib_dir.sh and
# 03swap_search_dirs.sh, but without optionally committing each automatically.

mangle="$(dirname "$0")/mangle_paths"

# config files go through swapdirs
find . \( -type d -path ./.git -prune \) \
	-o \
	\( -type f \( \
	-name 'configure*' -o -name '*.m4' -o -name '*.in' \
	\) \
	\! \( -name '*.mk' -o -name 'Makefile*' \) \
	-print \) \
	 | xargs "$mangle" --swapdirs --

# make files go through everything
find . \( -type d -path ./.git -prune \) \
	-o \
	\( -type f \( -name '*.mk' -o -name 'Makefile*' \) -print \) \
	| xargs "$mangle" --addlib --swapdirs --
